---
config:
  theme: redux
  themeVariables:
    nodeSpacing: 100
---
flowchart TD
 subgraph subGraph0["Finite element solution of mathematical model"]
    direction TB
        D["Assessment of accuracy of finite element solution of mathematical model"]
        C["<b>Finite Element Solution</b><br><br>
        <b>Choice of:</b><br>
        - Finite Elements<br>
        - Mesh Density<br>
        - Solution Parameters<br><br>
        <b>Representation of:</b><br>
        - Loading<br>
        - Boundary Conditions<br>
        - Etc.<br>"]
        E["Refine mesh, solution parameters, etc."]
  end
    A(["Physical Problem"]) --> B@{ label: "<b>Mathematical model</b><br>\n        Governed by differential equations<br>\n        <b>Assumptions on:</b><br>\n        <ul style=\"padding-left: 20px; text-align: left;\">\n            <li>Geometry</li>\n            <li>Kinematics</li>\n            <li>Material Law</li>\n            <li>Loading</li>\n            <li>Boundary Conditions</li>\n            <li>Etc.</li>\n        </ul>" }
    B --> C
    C --> D
    D --- E
    E --> C
    D --> F["Interpretation of results"]
    F --> G["Refine Analysis"] & I["Design Improvements Structural Optimization"]
    G --> H["Improve Mathematical Model"]
    H --> B
    I --> J["Change of Physical Problem"]
    J --> B
    B@{ shape: rect}
